### ISSUE TITLE
有没有交流群

### ISSUE THREAD

**Issue by chenny2024** [CreatorMC/MODSDKSping#2]

**Comment by CreatorMC** [comment]
没有针对此框架的群，我目前也没有建群的打算。有问题您可以提 issue，或者在开发者频道里艾特我之类的。我工作室倒是有几个交流群，如果您有兴趣也可以加一下。

魔灵工作室交流1群：545022387
魔灵工作室交流2群：565596621
魔灵工作室交流3群：931142420
魔灵工作室交流4群：752991929
（只加一个群就可以啦）
